sudo: false
language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

before_script:
  - phpize
  - ./configure --enable-scalar-objects
  - make

script: REPORT_EXIT_STATUS=1 php run-tests.php -p `which php` --show-diff -d extension=`pwd`/modules/scalar_objects.so -q
